In [1]:
from newsapi import NewsApiClient
import yfinance as yf

from Utils.clean_data_helper import *

'''
If unable to install pygooglenews, try
- pip install "setuptools<58.0"
- pip install feedparser --upgrade
- pip install setuptools
- pip install pygooglenews --upgrade
'''
from pygooglenews import GoogleNews
from tqdm import tqdm
import requests
import json

# Get S&P500 companies' tickers

In [2]:
response = requests.get('https://stockanalysis.com/list/sp-500-stocks/')
companies_info_df = pd.read_html(response.content)[0]
companies_info_df = companies_info_df.drop(columns=["No.", "Stock Price", "% Change", "Revenue"])
companies_info_df.to_excel("Data/SPY_companies_info.xlsx", index=False)

In [3]:
# tech stocks, pharma stocks, oil stocks, tobacco stocks and Market
tickers = companies_info_df["Symbol"].to_list()

# News Data Download
- newsapi has a limit of 2024-11-01 onwards
- pygoognews https://github.com/kotartemiy/pygooglenews
- Some other packages to try out: https://www.newscatcherapi.com/blog/python-web-scraping-libraries-to-mine-news-data

In [ ]:
# Looping over 500 tickers: this run will take a few hours
gn = GoogleNews(lang = 'en')

news_dfs = []
for ticker in tqdm(tickers):
    top = gn.search(ticker)
    entries = top["entries"]
    df_temp = clean_goog_news(entries)
    news_dfs += [df_temp.copy()]

In [6]:
news_dfs[0]

,date,title,source
0,"Wed, 04 Dec 2024 10:40:07 GMT",AAPL Stock Hits New High Despite Sales Slowdow...,https://news.google.com/rss/articles/CBMilwJBV...
1,"Fri, 06 Dec 2024 18:04:28 GMT",Why Apple Inc. (AAPL) Is the Best Beginner Sto...,https://news.google.com/rss/articles/CBMieEFVX...
2,"Fri, 06 Dec 2024 19:37:00 GMT",Best Dow Jones Stocks To Watch In December 202...,https://news.google.com/rss/articles/CBMidEFVX...
3,"Fri, 06 Dec 2024 15:55:00 GMT",Why Apple Doesn't Need Nvidia (NASDAQ:AAPL) - ...,https://news.google.com/rss/articles/CBMieEFVX...
4,"Wed, 04 Dec 2024 06:38:01 GMT",Apple (AAPL) Faces $1B Class Action Lawsuit Ov...,https://news.google.com/rss/articles/CBMingFBV...
...,...,...,...
94,"Wed, 04 Dec 2024 08:17:12 GMT",Thomasville National Bank Increases Stock Hold...,https://news.google.com/rss/articles/CBMixwFBV...
95,"Wed, 04 Dec 2024 16:47:28 GMT",Apple (NASDAQ:AAPL) Shares Up 0.3% Following A...,https://news.google.com/rss/articles/CBMirgFBV...
96,"Wed, 04 Dec 2024 08:17:19 GMT","Granite Harbor Advisors Inc. Buys 3,697 Shares...",https://news.google.com/rss/articles/CBMivwFBV...
97,"Tue, 26 Nov 2024 08:00:00 GMT",Apple Inc. (AAPL): Developing Advanced LLM Sir...,https://news.google.com/rss/articles/CBMihwFBV...
98,"Sun, 17 Nov 2024 08:00:00 GMT",Could Buying Apple Today Set You Up for Life? ...,https://news.google.com/rss/articles/CBMikAFBV...

## General News 
- Newscatcher for general news not targetted at specific stocks: https://github.com/kotartemiy/newscatcher

In [ ]:
topics = ['tech', 'news', 'business', 'science', 'finance', 'food', 'politics', 'economics', 'travel', 'entertainment', 'music', 'sport', 'world']
all_general_news = pd.DataFrame()

for t in tqdm(topics):
    news_temp = clean_newscatcher_news(t)
    all_general_news = pd.concat([all_general_news, news_temp])

  0%|          | 0/13 [00:00<?, ?it/s]

No. of URLs: 163
['facebook.com', 'twitter.com', 'theguardian.com', 'cnet.com', 'wired.com', 'digg.com', 'samsung.com', 'theverge.com', 'mashable.com', 'engadget.com', 'businesswire.com', 'lifehacker.com', 'utoronto.ca', 'eff.org', 'theregister.co.uk', 'pcworld.com', 'prweb.com', 'acm.org', 'techradar.com', 'ndtv.com', 'boingboing.net', 'popularmechanics.com', 'crunchbase.com', 'ycombinator.com', 'macrumors.com', 'cio.com', 'gigaom.com', 'ibtimes.co.uk', 'networkworld.com', 'extremetech.com', 'windows.com', 'dailydot.com', 'gsmarena.com', 'anandtech.com', 'slashgear.com', 'computerweekly.com', 'betanews.com', 'techdirt.com', 'houstonchronicle.com', 'techtimes.com', 'androidcentral.com', 'techspot.com', 'infoq.com', 'macmillan.com', 'windowscentral.com', 'neowin.net', 'phonearena.com', 'tmcnet.com', 'pocket-lint.com', 'cbinsights.com', 'theiet.org', 'thewirecutter.com', 'gizmodo.com.au', 'nerdist.com', 'itworld.com', 'internetsociety.org', 'themarysue.com', 'laptopmag.com', 'wccftech.com', 'ghacks.net', 'singularityhub.com', 'computing.co.uk', 'interestingengineering.com', 'sammobile.com', 'notebookcheck.net', 'guru3d.com', 'techhive.com', 'hothardware.com', 'siliconangle.com', 'information-age.com', 'ibtimes.co.in', 'elon.edu', 'tech.co', 'technewsworld.com', 'itpro.co.uk', 'itnews.com.au', 'lifehacker.com.au', 'cbronline.com', 'datacenterknowledge.com', 'bit-tech.net', 'nextgov.com', 'osnews.com', 'gcn.com', 'afterdawn.com', 'globalspec.com', 'wareable.com', 'privateinternetaccess.com', 'cheddar.com', 'hexus.net', 'mybroadband.co.za', 'komando.com', 'expertreviews.co.uk', 'fiercewireless.com', 'stuff.tv', 'thurrott.com', 'techxplore.com', 'gizchina.com', 'bitrebels.com', 'mobilesyrup.com', 'idg.com.au', 'itworldcanada.com', 'verdict.co.uk', 'webfoundation.org', 'bgr.in', 'businesstech.co.za', 'diginomica.com', 'streamingmedia.com', 'itbusiness.ca', 'betakit.com', 'vator.tv', 'arnnet.com.au', 'circleid.com', 'twice.com', 'gpsworld.com', 'tech.eu', 'cloudwards.net', 'whatech.com', 'itnewsafrica.com', 'ispreview.co.uk', 'windowslatest.com', 'gizbot.com', 'crn.com.au', 'geekzone.co.nz', 'knowtechie.com', 'overclockersclub.com', 'nocamels.com', 'alleywatch.com', 'digitalnewsasia.com', 'get.com', 'nerdreactor.com', 'techshout.com', 'semiengineering.com', 'channelweb.co.uk', 'themobileindian.com', 'design-reuse.com', 'technadu.com', 'goodgearguide.com.au', 'techcabal.com', 'socaltech.com', 'pcworld.co.nz', 'uktech.news', 'iafrikan.com', 'reseller.co.nz', 'geekculture.co', 'increment.com', 'ctovision.com', 'techgoondu.com', 'innotechtoday.com', 'contxto.com', 'unbox.ph', 'newsledge.com', 'techpoint.org', 'newsbytes.ph', 'inferse.com', 'stuff.co.za', 'tabletmonkeys.com', 'technowize.com', 'ehmac.ca', 'gadgetsmagazine.com.ph', 'thetechportal.in', 'jcs.org', 'telefonino.net', 'tailscale.com']

100%|██████████| 13/13 [56:31<00:00, 260.92s/it]

In [ ]:
all_general_news

,date,title,source,topic
0,"Tue, 03 Dec 2024 20:27:12 +0000",Powering AI innovation by acccelerating the ne...,https://sustainability.atmeta.com/blog/2024/12...,tech
1,"Mon, 02 Dec 2024 17:00:56 +0000",Meta Andromeda: Supercharging Advantage+ autom...,https://engineering.fb.com/2024/12/02/producti...,tech
2,"Tue, 19 Nov 2024 17:00:43 +0000",Sequence learning: A paradigm shift for person...,https://engineering.fb.com/2024/11/19/data-inf...,tech
3,"Tue, 12 Nov 2024 17:00:10 +0000",How Meta built large-scale cryptographic monit...,https://engineering.fb.com/2024/11/12/security...,tech
4,"Fri, 25 Oct 2024 16:32:59 +0000",Diff Authoring Time: Measuring developer produ...,https://engineering.fb.com/2024/10/25/develope...,tech
...,...,...,...,...
15,"Mon, 02 Dec 2024 08:36:00 GMT",Ambuja Cements moves closer to NET ZERO,https://www.worldcement.com/indian-subcontinen...,world
16,"Mon, 02 Dec 2024 08:32:00 GMT",Holcim signs agreement to sell its Nigerian bu...,https://www.worldcement.com/africa-middle-east...,world
17,"Fri, 29 Nov 2024 08:45:00 GMT",Play it Safe,https://www.worldcement.com/special-reports/29...,world
18,"Fri, 29 Nov 2024 08:39:00 GMT",30 years of heathland restoration at Rammamere...,https://www.worldcement.com/product-news/29112...,world
19,"Thu, 28 Nov 2024 10:02:00 GMT",FLSmidth to deliver two of the world’s largest...,https://www.worldcement.com/indian-subcontinen...,world

In [ ]:
with pd.ExcelWriter('Data/news_data.xlsx') as writer:
    for i, news_df in tqdm(enumerate(news_dfs)):
        news_df.to_excel(writer, sheet_name=tickers[i], index=False)
    all_general_news.to_excel(writer, sheet_name="General", index=False)
# Close the ExcelWriter object
writer.save()

# CapIQ Data
Data is acquired from SMU Library Website https://researchguides.smu.edu.sg/az.php?a=c

In [6]:
news = pd.ExcelFile('./Data/news_data.xlsx')
news_dict = {
    sheet_name: news.parse(sheet_name) for sheet_name in news.sheet_names if sheet_name != 'General'
}

all_general_news = pd.read_excel('./Data/news_data.xlsx', sheet_name="General")

In [7]:
capiq_df = pd.read_excel("Data/capiq_news_data.xlsx")
capiq_df = capiq_df.rename(columns = {"Key Developments By Date": "date",
                            "Key Development Headline": "title",
                            "Key Development Sources": "source",
                            "Primary Industry": "topic"
                            })

capiq_df =  capiq_df.drop(columns=["Key Developments by Type", "Key Development Situation", "Business Description"])

In [8]:
capiq_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448274 entries, 0 to 448273
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             448274 non-null  datetime64[ns]
 1   Company Name(s)  448274 non-null  object
 2   title            448274 non-null  object
 3   source           448274 non-null  object
 4   topic            448274 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 17.1+ MB

In [9]:
# Get ticker
capiq_df["Ticker"] = capiq_df["Company Name(s)"].str.replace(r'[^(]*\(|\)[^)]*', '')
capiq_df["Ticker"] = capiq_df["Ticker"].str.split(':').str[-1]
capiq_df["Ticker"] = capiq_df["Ticker"].str.replace(r'[^a-zA-Z]+', '')

capiq_df = capiq_df.drop(columns=["Company Name(s)"])

<ipython-input-9-8b62aaef2efa>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  capiq_df["Ticker"] = capiq_df["Company Name(s)"].str.replace(r'[^(]*\(|\)[^)]*', '')
<ipython-input-9-8b62aaef2efa>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  capiq_df["Ticker"] = capiq_df["Ticker"].str.replace(r'[^a-zA-Z]+', '')

In [11]:
capiq_df_tickers = capiq_df["Ticker"].unique().tolist()
found_tickers = 0
for t in tqdm(capiq_df_tickers):
    news_temp = capiq_df[capiq_df["Ticker"] == t]
    if t in news_dict:
        curr_news_df = news_dict[t].copy()
        match_topic_newscatcher = get_topic(news_temp["topic"].dropna().head(1).item()) # already sorted by ticker, just get the first non-NA topic
        curr_newscatcher = all_general_news[all_general_news["topic"] == match_topic_newscatcher].copy()
        news_dict[t] = pd.concat([curr_news_df, news_temp.drop(columns=["Ticker"]), curr_newscatcher])
        news_dict[t]["topic"] = match_topic_newscatcher
        found_tickers += 1
    else:
        continue
print(f"Found tickers: {found_tickers}")

100%|██████████| 3917/3917 [02:33<00:00, 25.46it/s]

Found tickers: 496

In [12]:
with pd.ExcelWriter('Data/news_data_final.xlsx') as writer:
    for ticker, news_df in tqdm(news_dict.items()):
        news_df.to_excel(writer, sheet_name=ticker, index=False)
# Close the ExcelWriter object
writer.save()

100%|██████████| 501/501 [01:29<00:00,  5.57it/s]
c:\Users\Ethelda\anaconda3\lib\site-packages\xlsxwriter\workbook.py:336: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

# Stocks Data Download
- Note that this is not the returns of the stocks data
- Let's focus on periods 2023-01-01 to 2024-12-01 for this project

In [4]:
stocks = yf.download(tickers, threads=True, group_by='ticker', start='2023-01-01', end='2024-12-01', multi_level_index=False)

[*********************100%***********************]  503 of 503 completed

2 Failed downloads:
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2023-01-01 -> 2024-12-01)')

In [5]:
stocks

Ticker            DAL                                                        \
Price            Open       High        Low      Close  Adj Close    Volume
Date
2023-01-03  33.250000  33.549999  32.340000  32.610001  32.105247   8640200
2023-01-04  32.950001  34.470001  32.939999  34.389999  33.857693  11318800
2023-01-05  34.689999  35.570000  34.520000  35.230000  34.684700  11332500
2023-01-06  35.189999  36.070000  35.099998  36.029999  35.472309  11110400
2023-01-09  36.540001  37.419998  36.349998  36.770000  36.200859  11251300
...               ...        ...        ...        ...        ...       ...
2024-11-22  63.450001  63.619999  62.900002  63.340000  63.340000   6625400
2024-11-25  64.330002  65.180000  63.970001  64.489998  64.489998   7901300
2024-11-26  64.860001  65.940002  63.990002  64.139999  64.139999   5499600
2024-11-27  64.070000  64.400002  63.230000  63.619999  63.619999   5557400
2024-11-29  63.650002  64.080002  63.560001  63.820000  63.820000   3111400

Ticker             MHK                                      ...         AJG  \
Price             Open        High         Low       Close  ...         Low
Date                                                        ...
2023-01-03  103.750000  107.400002  103.449997  106.860001  ...  185.410004
2023-01-04  109.050003  114.169998  107.849998  113.300003  ...  187.800003
2023-01-05  111.510002  113.330002  109.900002  113.040001  ...  185.449997
2023-01-06  113.720001  114.739998  112.070000  114.230003  ...  187.500000
2023-01-09  115.199997  115.290001  111.959999  112.199997  ...  190.809998
...                ...         ...         ...         ...  ...         ...
2024-11-22  138.309998  139.690002  138.080002  138.770004  ...  301.929993
2024-11-25  140.919998  146.929993  140.839996  145.029999  ...  300.769989
2024-11-26  142.639999  143.470001  139.259995  139.919998  ...  307.100006
2024-11-27  140.820007  142.880005  138.449997  139.100006  ...  311.619995
2024-11-29  140.539993  141.300003  138.289993  138.830002  ...  311.920013

Ticker                                               GS              \
Price            Close   Adj Close   Volume        Open        High
Date
2023-01-03  187.259995  183.706177   546600  345.500000  348.600006
2023-01-04  189.740005  186.139130   632900  348.029999  350.309998
2023-01-05  186.440002  182.901764   676600  344.250000  345.140015
2023-01-06  192.020004  188.375854   471300  347.299988  349.000000
2023-01-09  191.759995  188.120789   805700  351.880005  356.500000
...                ...         ...      ...         ...         ...
2024-11-22  304.290009  303.688599   626000  596.219971  603.940002
2024-11-25  306.390015  305.784454  2181300  608.789978  611.299988
2024-11-26  312.959991  312.341461  1538500  600.130005  607.190002
2024-11-27  315.160004  314.537109  1383200  607.679993  612.250000
2024-11-29  312.239990  311.622864   811900  609.309998  612.729980

Ticker
Price              Low       Close   Adj Close   Volume
Date
2023-01-03  342.809998  346.220001  327.647125  1589700
2023-01-04  345.079987  347.700012  329.047760  1881000
2023-01-05  340.140015  343.760010  325.319122  1397800
2023-01-06  340.950012  348.079987  329.407379  3097800
2023-01-09  349.500000  353.000000  334.063446  1989000
...                ...         ...         ...      ...
2024-11-22  594.440002  602.780029  599.808594  1733700
2024-11-25  598.830017  603.030029  600.057312  2940800
2024-11-26  593.000000  605.500000  602.515137  2846500
2024-11-27  603.280029  605.429993  602.445435  1424500
2024-11-29  607.059998  608.570007  605.570007  1170200

[481 rows x 3018 columns]

In [86]:
ticker_tz_df = pd.DataFrame()
for t in tickers:
    try:
        ticker_info = yf.Ticker(t)
        ticker_tz = ticker_info.info['timeZoneShortName']
        ticker_tz_temp_df = pd.DataFrame({'Ticker':[t], 'tz':[ticker_tz]})
        ticker_tz_df = pd.concat([ticker_tz_df, ticker_tz_temp_df])
    except:
        print(f'No timezone info for {t}')

No timezone info for BRK.B

In [90]:
print(f'Timezones of SPY stocks include: {ticker_tz_df.tz.unique()}')

Timezones of SPY stocks include: ['EST']

In [91]:
market = yf.download(["SPY"], threads=True, group_by='ticker', start='2023-01-01', end='2024-12-01', multi_level_index=False)

[*********************100%***********************]  1 of 1 completed

In [92]:
market

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-01-03,384.369995,386.429993,377.829987,380.820007,371.614441,74850700
2023-01-04,383.179993,385.880005,380.000000,383.760010,374.483368,85934100
2023-01-05,381.720001,381.839996,378.760010,379.380005,370.209198,76970500
2023-01-06,382.609985,389.250000,379.410004,388.079987,378.698883,104189600
2023-01-09,390.369995,393.700012,387.670013,387.859985,378.484192,73978100
...,...,...,...,...,...,...
2024-11-22,593.659973,596.150024,593.150024,595.510010,595.510010,38226400
2024-11-25,599.520020,600.859985,595.200012,597.530029,597.530029,42441400
2024-11-26,598.799988,601.330017,598.070007,600.650024,600.650024,45621300
2024-11-27,600.460022,600.849976,597.280029,598.830017,598.830017,34000200
2024-11-29,599.659973,603.349976,599.380005,602.549988,602.549988,30177400

In [11]:
stocks.to_excel("Data/stocks_data.xlsx")

In [ ]:
market.to_excel("Data/market_data.xlsx")