In [56]:
from newsapi import NewsApiClient
import yfinance as yf

from Utils.clean_data_helper import *

'''
If unable to install pygooglenews, try
- pip install "setuptools<58.0"
- pip install feedparser --upgrade
- pip install setuptools
- pip install pygooglenews --upgrade
'''
from pygooglenews import GoogleNews
from tqdm import tqdm
import requests
import json

# Get S&P500 companies' tickers

In [57]:
response = requests.get('https://stockanalysis.com/list/sp-500-stocks/')
companies_info_df = pd.read_html(response.content)[0]
companies_info_df = companies_info_df.drop(columns=["No.", "Stock Price", "% Change", "Revenue"])
companies_info_df.to_excel("Data/SPY_companies_info.xlsx", index=False)

In [58]:
# tech stocks, pharma stocks, oil stocks, tobacco stocks and Market
tickers = companies_info_df["Symbol"].to_list()

# News Data Download
- newsapi has a limit of 2024-11-01 onwards
- pygoognews https://github.com/kotartemiy/pygooglenews
- Some other packages to try out: https://www.newscatcherapi.com/blog/python-web-scraping-libraries-to-mine-news-data

In [ ]:
gn = GoogleNews(lang = 'en')

news_dfs = []
for ticker in tqdm(tickers):
    top = gn.search(ticker)
    entries = top["entries"]
    df_temp = clean_goog_news(entries)
    news_dfs += [df_temp.copy()]

In [6]:
news_dfs[0]

,date,title,source
0,"Wed, 04 Dec 2024 10:40:07 GMT",AAPL Stock Hits New High Despite Sales Slowdow...,https://news.google.com/rss/articles/CBMilwJBV...
1,"Fri, 06 Dec 2024 18:04:28 GMT",Why Apple Inc. (AAPL) Is the Best Beginner Sto...,https://news.google.com/rss/articles/CBMieEFVX...
2,"Fri, 06 Dec 2024 19:37:00 GMT",Best Dow Jones Stocks To Watch In December 202...,https://news.google.com/rss/articles/CBMidEFVX...
3,"Fri, 06 Dec 2024 15:55:00 GMT",Why Apple Doesn't Need Nvidia (NASDAQ:AAPL) - ...,https://news.google.com/rss/articles/CBMieEFVX...
4,"Wed, 04 Dec 2024 06:38:01 GMT",Apple (AAPL) Faces $1B Class Action Lawsuit Ov...,https://news.google.com/rss/articles/CBMingFBV...
...,...,...,...
94,"Wed, 04 Dec 2024 08:17:12 GMT",Thomasville National Bank Increases Stock Hold...,https://news.google.com/rss/articles/CBMixwFBV...
95,"Wed, 04 Dec 2024 16:47:28 GMT",Apple (NASDAQ:AAPL) Shares Up 0.3% Following A...,https://news.google.com/rss/articles/CBMirgFBV...
96,"Wed, 04 Dec 2024 08:17:19 GMT","Granite Harbor Advisors Inc. Buys 3,697 Shares...",https://news.google.com/rss/articles/CBMivwFBV...
97,"Tue, 26 Nov 2024 08:00:00 GMT",Apple Inc. (AAPL): Developing Advanced LLM Sir...,https://news.google.com/rss/articles/CBMihwFBV...
98,"Sun, 17 Nov 2024 08:00:00 GMT",Could Buying Apple Today Set You Up for Life? ...,https://news.google.com/rss/articles/CBMikAFBV...

## General News 
- Newscatcher for general news not targetted at specific stocks: https://github.com/kotartemiy/newscatcher

In [7]:
# topics supported: 'tech', 'news', 'business', 'science', 'finance', 'food', 'politics', 'economics', 'travel', 'entertainment', 'music', 'sport', 'world'

finance_news = clean_newscatcher_news('finance')
business_news = clean_newscatcher_news('business')
economics_news = clean_newscatcher_news('economics')
tech_news = clean_newscatcher_news('tech')
politics_news = clean_newscatcher_news('politics')

No. of URLs: 80
['marketwatch.com', 'investopedia.com', 'seekingalpha.com', 'xe.com', 'thestreet.com', 'financialpost.com', 'investing.com', 'kiplinger.com', 'benzinga.com', 'thisismoney.co.uk', 'cityam.com', 'daveramsey.com', 'fin24.com', 'smartasset.com', 'investorplace.com', 'institutionalinvestor.com', 'ritholtz.com', 'marketrealist.com', 'pionline.com', 'efinancialcareers.com', 'marketoracle.co.uk', 'moneymorning.com', 'financial-planning.com', 'citywire.co.uk', 'wealthmanagement.com', 'investmentwatchblog.com', 'moneytalksnews.com', 'morningstar.co.uk', 'insidermonkey.com', 'risk.net', 'realclearmarkets.com', 'financialsamurai.com', 'worldfinance.com', 'armstrongeconomics.com', 'savingadvice.com', 'fool.co.uk', 'elliottwave.com', 'simplywall.st', 'kitces.com', 'etfdailynews.com', 'investmentweek.co.uk', 'globalcapital.com', 'interest.co.nz', 'ai-cio.com', 'fool.ca', 'learnbonds.com', 'wallstreetdaily.com', 'abladvisor.com', 'fool.com.au', 'investmentexecutive.com', 'investmentu.com', 'finanzen.ch', 'financeasia.com', 'mybudget360.com', 'wallstreetpit.com', 'swfinstitute.org', 'wealthdaily.com', 'waterstechnology.com', 'smallcaps.com.au', 'finews.asia', 'marketsmedia.com', 'moneymanagement.com.au', 'smarteranalyst.com', 'moneyobserver.com', 'trustnet.com', 'themiddlemarket.com', 'finews.com', 'insidefutures.com', 'stockmarketwire.com', 'dailyreckoning.com.au', 'thetradenews.com', 'equitymaster.com', 'financialreporter.co.uk', 'ringgitplus.com', 'hedgeco.net', 'brokernews.com.au', 'theadviser.com.au', 'cnafinance.com', 'asianinvestor.net', 'dailyalts.com']

In [8]:
all_news = pd.concat([finance_news, business_news, economics_news, tech_news, politics_news])
all_news

,date,title,source,topic
0,"Sat, 07 Dec 2024 15:50:00 GMT",Millennials are finally joining the 401(k) mil...,https://www.marketwatch.com/story/millennials-...,finance
1,"Sat, 07 Dec 2024 15:41:00 GMT",These stocks aren’t likely to beat the S&P 500...,https://www.marketwatch.com/story/20-stocks-li...,finance
2,"Sat, 07 Dec 2024 15:38:00 GMT",The aging U.S. power grid is slowing Big Tech’...,https://www.marketwatch.com/story/big-techs-da...,finance
3,"Sat, 07 Dec 2024 15:36:00 GMT",The Social Security Fairness Act is incredibly...,https://www.marketwatch.com/story/the-social-s...,finance
4,"Sat, 07 Dec 2024 15:09:00 GMT",A retirement expert’s best advice? Don’t retire.,https://www.marketwatch.com/story/a-retirement...,finance
...,...,...,...,...
1318,2024-03-03T05:47:23Z,The world of bullshit we’ve built: Reflections...,https://clubtroppo.com.au/2024/03/03/the-stran...,politics
1319,2024-02-13T04:48:17Z,Figuring out the strange new rules of resource...,https://clubtroppo.com.au/2024/02/13/figuring-...,politics
1320,2023-12-27T08:28:06Z,William Hague gets on board,https://clubtroppo.com.au/2023/12/27/william-h...,politics
1321,2023-12-23T05:49:25Z,Michael Polanyi in 1960 on Teilhard de Chardin...,https://clubtroppo.com.au/2023/12/23/michael-p...,politics
1322,2023-11-25T04:30:31Z,Democracy: doing it for ourselves,https://clubtroppo.com.au/2023/11/25/democracy...,politics

# Stocks Data Download
- Note that this is not the returns of the stocks data
- Let's focus on periods 2023-01-01 to 2024-12-01 for this project

In [59]:
stocks = yf.download(tickers, threads=True, group_by='ticker', start='2023-01-01', end='2024-12-01', multi_level_index=False)

[*********************100%***********************]  503 of 503 completed

2 Failed downloads:
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2023-01-01 -> 2024-12-01)')

In [86]:
ticker_tz_df = pd.DataFrame()
for t in tickers:
    try:
        ticker_info = yf.Ticker(t)
        ticker_tz = ticker_info.info['timeZoneShortName']
        ticker_tz_temp_df = pd.DataFrame({'Ticker':[t], 'tz':[ticker_tz]})
        ticker_tz_df = pd.concat([ticker_tz_df, ticker_tz_temp_df])
    except:
        print(f'No timezone info for {t}')

No timezone info for BRK.B

In [90]:
print(f'Timezones of SPY stocks include: {ticker_tz_df.tz.unique()}')

Timezones of SPY stocks include: ['EST']

In [52]:
stocks

Ticker            GOOG                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2023-01-03   89.830002   91.550003   89.019997   89.699997   89.480247
2023-01-04   91.010002   91.239998   87.800003   88.709999   88.492683
2023-01-05   88.070000   88.209999   86.559998   86.769997   86.557426
2023-01-06   87.360001   88.470001   85.570000   88.160004   87.944031
2023-01-09   89.195000   90.830002   88.580002   88.800003   88.582458
...                ...         ...         ...         ...         ...
2024-11-22  167.160004  168.264999  165.710007  166.570007  166.570007
2024-11-25  167.990005  170.460007  167.399994  169.429993  169.429993
2024-11-26  169.490005  171.494995  169.429993  170.619995  170.619995
2024-11-27  170.679993  171.139999  169.669998  170.820007  170.820007
2024-11-29  170.059998  170.869995  168.750000  170.490005  170.490005

Ticker                       PTC                                      ...  \
Price         Volume        Open        High         Low       Close  ...
Date                                                                  ...
2023-01-03  20738500  121.250000  123.059998  118.599998  119.650002  ...
2023-01-04  27046500  120.440002  122.230003  119.690002  121.970001  ...
2023-01-05  23136100  120.769997  120.989998  118.209999  120.050003  ...
2023-01-06  26612600  121.379997  123.190002  119.019997  122.690002  ...
2023-01-09  22996700  123.870003  128.360001  123.870003  125.959999  ...
...              ...         ...         ...         ...         ...  ...
2024-11-22  24497000  192.649994  197.830002  191.979996  197.639999  ...
2024-11-25  21395700  197.809998  201.660004  197.809998  200.589996  ...
2024-11-26  14937500  200.490005  200.679993  198.460007  199.259995  ...
2024-11-27  12433400  198.389999  199.419998  197.029999  199.009995  ...
2024-11-29   9250700  199.449997  200.449997  197.529999  200.059998  ...

Ticker             ZTS                                         TAP             \
Price              Low       Close   Adj Close   Volume       Open       High
Date
2023-01-03  145.210007  146.850006  144.095428  1840600  50.549999  50.669998
2023-01-04  147.960007  148.960007  146.165848  1796100  49.779999  51.580002
2023-01-05  144.270004  145.449997  142.721664  1560900  50.459999  50.759998
2023-01-06  141.520004  147.639999  144.870590  1761200  50.860001  51.189999
2023-01-09  147.000000  147.059998  144.301483  1700500  50.730000  51.180000
...                ...         ...         ...      ...        ...        ...
2024-11-22  176.279999  176.960007  176.960007  1854600  60.459999  60.919998
2024-11-25  176.149994  178.710007  178.710007  4558300  60.840000  62.220001
2024-11-26  174.839996  175.699997  175.699997  2539600  60.700001  61.549999
2024-11-27  175.000000  176.740005  176.740005  2315800  61.660000  62.070000
2024-11-29  175.240005  175.250000  175.250000  1543400  61.250000  62.430000

Ticker
Price             Low      Close  Adj Close   Volume
Date
2023-01-03  48.660000  49.439999  46.626884  2770400
2023-01-04  49.660000  51.360001  48.437637  1672100
2023-01-05  49.209999  49.580002  46.758919  1849800
2023-01-06  50.450001  50.880001  47.984943  2145000
2023-01-09  50.160000  50.209999  47.353073  1466700
...               ...        ...        ...      ...
2024-11-22  60.160000  60.360001  59.927452  1488300
2024-11-25  60.650002  60.669998  60.235229  2848800
2024-11-26  60.360001  61.410000  60.969925  2132700
2024-11-27  61.150002  61.250000  60.811073  1438000
2024-11-29  61.009998  62.060001  61.615269   988200

[481 rows x 3018 columns]

In [91]:
market = yf.download(["SPY"], threads=True, group_by='ticker', start='2023-01-01', end='2024-12-01', multi_level_index=False)

[*********************100%***********************]  1 of 1 completed

In [92]:
market

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-01-03,384.369995,386.429993,377.829987,380.820007,371.614441,74850700
2023-01-04,383.179993,385.880005,380.000000,383.760010,374.483368,85934100
2023-01-05,381.720001,381.839996,378.760010,379.380005,370.209198,76970500
2023-01-06,382.609985,389.250000,379.410004,388.079987,378.698883,104189600
2023-01-09,390.369995,393.700012,387.670013,387.859985,378.484192,73978100
...,...,...,...,...,...,...
2024-11-22,593.659973,596.150024,593.150024,595.510010,595.510010,38226400
2024-11-25,599.520020,600.859985,595.200012,597.530029,597.530029,42441400
2024-11-26,598.799988,601.330017,598.070007,600.650024,600.650024,45621300
2024-11-27,600.460022,600.849976,597.280029,598.830017,598.830017,34000200
2024-11-29,599.659973,603.349976,599.380005,602.549988,602.549988,30177400

# Save Data

In [10]:
with pd.ExcelWriter('Data/news_data.xlsx') as writer:
    for i, news_df in tqdm(enumerate(news_dfs)):
        news_df.to_excel(writer, sheet_name=tickers[i], index=False)
    all_news.to_excel(writer, sheet_name="General", index=False)
# Close the ExcelWriter object
writer.save()

501it [00:03, 150.64it/s]
c:\Users\Ethelda\anaconda3\lib\site-packages\xlsxwriter\workbook.py:336: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

In [11]:
stocks.to_excel("Data/stocks_data.xlsx")

In [ ]:
market.to_excel("Data/market_data.xlsx")