In [1]:
from newsapi import NewsApiClient
import yfinance as yf

from Utils.clean_data_helper import *

'''
If unable to install pygooglenews, try
- pip install "setuptools<58.0"
- pip install feedparser --upgrade
- pip install setuptools
- pip install pygooglenews --upgrade
'''
from pygooglenews import GoogleNews
from tqdm import tqdm
import requests
import json

# Get S&P500 companies' tickers

In [2]:
response = requests.get('https://stockanalysis.com/list/sp-500-stocks/')
companies_info_df = pd.read_html(response.content)[0]
companies_info_df = companies_info_df.drop(columns=["No.", "Stock Price", "% Change", "Revenue"])
companies_info_df.to_excel("Data/SPY_companies_info.xlsx", index=False)

In [3]:
# tech stocks, pharma stocks, oil stocks, tobacco stocks and Market
tickers = companies_info_df["Symbol"].to_list()

# News Data Download
- newsapi has a limit of 2024-11-01 onwards
- pygoognews https://github.com/kotartemiy/pygooglenews
- Some other packages to try out: https://www.newscatcherapi.com/blog/python-web-scraping-libraries-to-mine-news-data

In [ ]:
gn = GoogleNews(lang = 'en')

news_dfs = []
for ticker in tqdm(tickers):
    top = gn.search(ticker)
    entries = top["entries"]
    df_temp = clean_goog_news(entries)
    news_dfs += [df_temp.copy()]

In [6]:
news_dfs[0]

,date,title,source
0,"Wed, 04 Dec 2024 10:40:07 GMT",AAPL Stock Hits New High Despite Sales Slowdow...,https://news.google.com/rss/articles/CBMilwJBV...
1,"Fri, 06 Dec 2024 18:04:28 GMT",Why Apple Inc. (AAPL) Is the Best Beginner Sto...,https://news.google.com/rss/articles/CBMieEFVX...
2,"Fri, 06 Dec 2024 19:37:00 GMT",Best Dow Jones Stocks To Watch In December 202...,https://news.google.com/rss/articles/CBMidEFVX...
3,"Fri, 06 Dec 2024 15:55:00 GMT",Why Apple Doesn't Need Nvidia (NASDAQ:AAPL) - ...,https://news.google.com/rss/articles/CBMieEFVX...
4,"Wed, 04 Dec 2024 06:38:01 GMT",Apple (AAPL) Faces $1B Class Action Lawsuit Ov...,https://news.google.com/rss/articles/CBMingFBV...
...,...,...,...
94,"Wed, 04 Dec 2024 08:17:12 GMT",Thomasville National Bank Increases Stock Hold...,https://news.google.com/rss/articles/CBMixwFBV...
95,"Wed, 04 Dec 2024 16:47:28 GMT",Apple (NASDAQ:AAPL) Shares Up 0.3% Following A...,https://news.google.com/rss/articles/CBMirgFBV...
96,"Wed, 04 Dec 2024 08:17:19 GMT","Granite Harbor Advisors Inc. Buys 3,697 Shares...",https://news.google.com/rss/articles/CBMivwFBV...
97,"Tue, 26 Nov 2024 08:00:00 GMT",Apple Inc. (AAPL): Developing Advanced LLM Sir...,https://news.google.com/rss/articles/CBMihwFBV...
98,"Sun, 17 Nov 2024 08:00:00 GMT",Could Buying Apple Today Set You Up for Life? ...,https://news.google.com/rss/articles/CBMikAFBV...

## General News 
- Newscatcher for general news not targetted at specific stocks: https://github.com/kotartemiy/newscatcher

In [7]:
# topics supported: 'tech', 'news', 'business', 'science', 'finance', 'food', 'politics', 'economics', 'travel', 'entertainment', 'music', 'sport', 'world'

finance_news = clean_newscatcher_news('finance')
business_news = clean_newscatcher_news('business')
economics_news = clean_newscatcher_news('economics')
tech_news = clean_newscatcher_news('tech')
politics_news = clean_newscatcher_news('politics')

No. of URLs: 80
['marketwatch.com', 'investopedia.com', 'seekingalpha.com', 'xe.com', 'thestreet.com', 'financialpost.com', 'investing.com', 'kiplinger.com', 'benzinga.com', 'thisismoney.co.uk', 'cityam.com', 'daveramsey.com', 'fin24.com', 'smartasset.com', 'investorplace.com', 'institutionalinvestor.com', 'ritholtz.com', 'marketrealist.com', 'pionline.com', 'efinancialcareers.com', 'marketoracle.co.uk', 'moneymorning.com', 'financial-planning.com', 'citywire.co.uk', 'wealthmanagement.com', 'investmentwatchblog.com', 'moneytalksnews.com', 'morningstar.co.uk', 'insidermonkey.com', 'risk.net', 'realclearmarkets.com', 'financialsamurai.com', 'worldfinance.com', 'armstrongeconomics.com', 'savingadvice.com', 'fool.co.uk', 'elliottwave.com', 'simplywall.st', 'kitces.com', 'etfdailynews.com', 'investmentweek.co.uk', 'globalcapital.com', 'interest.co.nz', 'ai-cio.com', 'fool.ca', 'learnbonds.com', 'wallstreetdaily.com', 'abladvisor.com', 'fool.com.au', 'investmentexecutive.com', 'investmentu.com', 'finanzen.ch', 'financeasia.com', 'mybudget360.com', 'wallstreetpit.com', 'swfinstitute.org', 'wealthdaily.com', 'waterstechnology.com', 'smallcaps.com.au', 'finews.asia', 'marketsmedia.com', 'moneymanagement.com.au', 'smarteranalyst.com', 'moneyobserver.com', 'trustnet.com', 'themiddlemarket.com', 'finews.com', 'insidefutures.com', 'stockmarketwire.com', 'dailyreckoning.com.au', 'thetradenews.com', 'equitymaster.com', 'financialreporter.co.uk', 'ringgitplus.com', 'hedgeco.net', 'brokernews.com.au', 'theadviser.com.au', 'cnafinance.com', 'asianinvestor.net', 'dailyalts.com']

In [8]:
all_news = pd.concat([finance_news, business_news, economics_news, tech_news, politics_news])
all_news

,date,title,source,topic
0,"Sat, 07 Dec 2024 15:50:00 GMT",Millennials are finally joining the 401(k) mil...,https://www.marketwatch.com/story/millennials-...,finance
1,"Sat, 07 Dec 2024 15:41:00 GMT",These stocks aren’t likely to beat the S&P 500...,https://www.marketwatch.com/story/20-stocks-li...,finance
2,"Sat, 07 Dec 2024 15:38:00 GMT",The aging U.S. power grid is slowing Big Tech’...,https://www.marketwatch.com/story/big-techs-da...,finance
3,"Sat, 07 Dec 2024 15:36:00 GMT",The Social Security Fairness Act is incredibly...,https://www.marketwatch.com/story/the-social-s...,finance
4,"Sat, 07 Dec 2024 15:09:00 GMT",A retirement expert’s best advice? Don’t retire.,https://www.marketwatch.com/story/a-retirement...,finance
...,...,...,...,...
1318,2024-03-03T05:47:23Z,The world of bullshit we’ve built: Reflections...,https://clubtroppo.com.au/2024/03/03/the-stran...,politics
1319,2024-02-13T04:48:17Z,Figuring out the strange new rules of resource...,https://clubtroppo.com.au/2024/02/13/figuring-...,politics
1320,2023-12-27T08:28:06Z,William Hague gets on board,https://clubtroppo.com.au/2023/12/27/william-h...,politics
1321,2023-12-23T05:49:25Z,Michael Polanyi in 1960 on Teilhard de Chardin...,https://clubtroppo.com.au/2023/12/23/michael-p...,politics
1322,2023-11-25T04:30:31Z,Democracy: doing it for ourselves,https://clubtroppo.com.au/2023/11/25/democracy...,politics

# Stocks Data Download
- Note that this is not the returns of the stocks data
- Let's focus on periods 2023-01-01 to 2024-12-01 for this project

In [ ]:
stocks = yf.download(tickers, threads=True, group_by='ticker', start='2023-01-01', end='2024-12-01')

[**********************60%****                   ]  301 of 503 completed

In [ ]:
stocks

# Save Data

In [ ]:
with pd.ExcelWriter('Data/news_data.xlsx') as writer:
    for i, news_df in tqdm(enumerate(news_dfs)):
        news_df.to_excel(writer, sheet_name=tickers[i], index=False)
    all_news.to_excel(writer, sheet_name="General", index=False)
# Close the ExcelWriter object
writer.save()

c:\Users\Ethelda\anaconda3\lib\site-packages\xlsxwriter\workbook.py:336: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

In [ ]:
stocks.to_excel("Data/stocks_data.xlsx")