In [15]:
from newsapi import NewsApiClient
import yfinance as yf

from Utils.clean_data_helper import *

'''
If unable to install pygooglenews, try
- pip install "setuptools<58.0"
- pip install feedparser --upgrade
- pip install setuptools
- pip install pygooglenews --upgrade
'''
from pygooglenews import GoogleNews
from tqdm import tqdm
import requests
import json

import warnings
warnings.filterwarnings('ignore')

# Get S&P500 companies' tickers

In [4]:
# response = requests.get('https://stockanalysis.com/list/sp-500-stocks/')
# companies_info_df = pd.read_html(response.content)[0]
# companies_info_df = companies_info_df.drop(columns=["No.", "Stock Price", "% Change", "Revenue"])
# companies_info_df.to_csv("Data Updated/SPY_companies_info.csv", index=False)

In [5]:
# # tech stocks, pharma stocks, oil stocks, tobacco stocks and Market
# tickers = companies_info_df["Symbol"].to_list()

# News Data Download
- newsapi has a limit of 2024-11-01 onwards
- pygoognews https://github.com/kotartemiy/pygooglenews
- Some other packages to try out: https://www.newscatcherapi.com/blog/python-web-scraping-libraries-to-mine-news-data

In [8]:
# # Looping over 500 tickers: this run will take a few hours
# gn = GoogleNews(lang = 'en')
#
# news_dfs = []
# for ticker in tqdm(tickers):
#     top = gn.search(ticker)
#     entries = top["entries"]
#     df_temp = clean_goog_news(entries)
#     df_temp["date"] = df_temp["date"].apply(lambda d: pd.to_datetime(d, errors='coerce').date())
#     df_temp = df_temp.dropna()
#     df_temp["ticker"] = ticker
#     news_dfs += [df_temp.copy()]
#
# goog_news_df = pd.concat(news_dfs, ignore_index=True)
# goog_news_df

100%|██████████| 503/503 [3:41:23<00:00, 26.41s/it]

,date,title,source,ticker
0,2024-12-10,Analyst Says Apple (AAPL) Stock is Not a ‘Holi...,https://news.google.com/rss/articles/CBMigAFBV...,AAPL
1,2024-12-11,S&P 500 Gains and Losses Today: Broadcom Soars...,https://news.google.com/rss/articles/CBMivgFBV...,AAPL
2,2024-12-11,Apple's AI Breakthrough: Broadcom Shares Soar ...,https://news.google.com/rss/articles/CBMijAFBV...,AAPL
3,2024-12-12,Apple Moves Ahead In AI With New Broadcom Deal...,https://news.google.com/rss/articles/CBMikAFBV...,AAPL
4,2024-12-12,Apple (AAPL) Is Developing Its Own Custom Micr...,https://news.google.com/rss/articles/CBMirgFBV...,AAPL
...,...,...,...,...
49661,2018-01-24,"""America's Next Top Model"" Makes Contestant Wi...",https://news.google.com/rss/articles/CBMilgFBV...,AMTM
49662,2022-04-12,'America's Next Top Model' Alums Allege Trauma...,https://news.google.com/rss/articles/CBMi5AFBV...,AMTM
49663,2021-12-30,Why ‘America’s Next Top Model’ is getting slam...,https://news.google.com/rss/articles/CBMijwFBV...,AMTM
49664,2021-12-05,America's Next Top Model: Tyra Banks' 8 Iconic...,https://news.google.com/rss/articles/CBMifEFVX...,AMTM
49665,2014-03-20,What’s the Best Reality Show Ever? Round 2: Am...,https://news.google.com/rss/articles/CBMimwFBV...,AMTM

In [27]:
# goog_news_df.to_csv("Data Updated/goog_news_df.csv")

In [28]:
# # Clean and format dataset
# def remove_ticker_substrings(text):
#     for ticker in tickers:
#         text = text.replace(f"({ticker})", "")
#     return text
#
# goog_news_df = goog_news_df.dropna()
# goog_news_df = goog_news_df.drop_duplicates().reset_index(drop=True)
# goog_news_df["date"] = goog_news_df["date"].apply(lambda d: pd.to_datetime(d, errors='coerce', utc=True).date())
# goog_news_df["title"] = goog_news_df["title"].str.replace(r"\('\w+':'\w+'\)", "", regex=True)
# goog_news_df["title"] = remove_ticker_substrings(goog_news_df["title"])

# CapIQ Data
Financial data is acquired from Capital IQ from dates 01-01-2024 to 04-12-2024

In [16]:
capiq_df = pd.read_excel(r"C:\Users\Tylus\Desktop\capiq_news_data.xlsx")
capiq_df = capiq_df.rename(columns = {"Key Developments By Date": "date",
                            "Key Development Headline": "title",
                            "Key Development Sources": "source",
                            "Primary Industry": "topic"
                            })
capiq_df =  capiq_df.drop(columns=["Key Developments by Type", "Key Development Situation"])

In [17]:
# Keep only headlines for individual stocks and get ticker
capiq_df["ticker"] = capiq_df["Company Name(s)"].str.findall(r'\([A-Za-z]+:[A-Za-z]+\)').apply(','.join)
capiq_df = capiq_df[capiq_df["ticker"].str.count(',') == 0]
capiq_df["ticker"] = capiq_df["ticker"].str.extract(r':([A-Za-z]+)\)')

# Clean and format dataset
capiq_df = capiq_df[["date", "title", "source", "ticker"]]
capiq_df = capiq_df.dropna()
capiq_df = capiq_df.drop_duplicates().reset_index(drop=True)
capiq_df["title"] = capiq_df["title"].str.replace(r"\([A-Za-z]+:[A-Za-z]+\)", "", regex=True)
capiq_df

,date,title,source,ticker
0,2014-01-01,Motorola Solutions to Provide IDF's Battlefiel...,Other,MSI
1,2014-01-01,TE Connectivity Brings Advanced Mobile Service...,Business Wire,TEL
2,2014-01-01,Leidos Holdings Receives Follow-On Contract fr...,Datamonitor NewsWire,LDOS
3,2014-01-01,MarketAxess Holdings Inc.'s Equity Buyback ann...,Capital IQ Buybacks Database,MKTX
4,2014-01-02,Southwest Airlines Orders Aviation Partners Bo...,PR Newswire,LUV
...,...,...,...,...
408745,2024-12-04,CSX Corporation Presents at UBS Global Industr...,PR Newswire; Business Wire; GlobeNewswire; Com...,CSX
408746,2024-12-04,UnitedHealth Group Incorporated - Analyst/Inve...,Business Wire,UNH
408747,2024-12-04,LyondellBasell Industries N.V. Presents at Gol...,PR Newswire; Business Wire; GlobeNewswire; Com...,LYB
408748,2024-12-04,Freeport-McMoRan Inc. Presents at Mines and Mo...,Company Website,FCX
408749,2024-12-04,Intuit Inc. Presents at Wells Fargo 8th Annual...,Business Wire; GlobeNewswire; Company Website,INTU

In [18]:
capiq_df.to_csv("Data Updated/capiq_df.csv")

# Merging CapIQ and PyGoogleNews

In [ ]:
# news_all_df = goog_news_df.append(capiq_df).sort_values("date", ascending=True).reset_index(drop=True)
# news_all_df["date"] = news_all_df["date"].apply(lambda d: pd.to_datetime(d, errors='coerce'))
# news_all_df

In [72]:
# news_all_df.to_csv("Data Updated/news_all_df.csv")

# Train Test Split and Removing Similar News

In [19]:
news_all_df = capiq_df
news_all_df["date"] = news_all_df["date"].apply(lambda d: pd.to_datetime(d, errors='coerce'))

In [20]:
# Split dataset in train set (for headlines before 2024) and test set (for headlines in 2024)
news_train_df = news_all_df[news_all_df["date"].dt.year < 2024].copy()
news_test_df = news_all_df[news_all_df["date"].dt.year >= 2024].copy()

In [ ]:
news_all_df.to_csv("Data Updated/news_all_df.csv")
news_train_df.to_csv("Data Updated/news_train_df.csv")
news_test_df.to_csv("Data Updated/_news_test_df.csv")

In [25]:
def remove_similar_news_optimised(df, col, date_col, threshold=0.80, window_days=20):
    df = df.sort_values(by=date_col).reset_index(drop=True)

    vectorizer = CountVectorizer()
    vectors = vectorizer.fit_transform(df[col])
    cos_sim = cosine_similarity(vectors)

    dates = pd.to_datetime(df[date_col])
    to_remove = set()

    for r in range(len(cos_sim)):
        if r in to_remove:
            continue

        for c in range(r + 1, len(cos_sim)):
            if c in to_remove:
                continue

            # Check if the two entries are within the date window
            if abs((dates.iloc[r] - dates.iloc[c]).days) > window_days:
                continue

            # Check similarity
            if cos_sim[r, c] > threshold:
                to_remove.add(c)

    valid_indices = set(df.index)
    to_remove = to_remove.intersection(valid_indices)
    df = df.drop(index=to_remove).reset_index(drop=True)
    return df

In [26]:
dfs = [news_train_df, news_test_df]

for idx, df in enumerate(dfs, start=1):
    chunked_results = []
    total_tickers = len(df['ticker'].unique())

    for i, (ticker, group) in enumerate(df.groupby("ticker"), start=1):
        print(f"Processing ticker {i}/{total_tickers}: {ticker} with {len(group)} articles...")
        group = group.sort_values(by="date").reset_index(drop=True)
        filtered_group = remove_similar_news_optimised(group, "title", "date", threshold=0.80, window_days=20)
        chunked_results.append(filtered_group)
        print(f"Completed processing ticker {i}/{total_tickers}: {ticker}. Filtered articles: {len(filtered_group)}.")

    filtered_df = pd.concat(chunked_results).reset_index(drop=True)
    print(f"Finished processing all groups in dataset {idx}. Final DataFrame has {len(filtered_df)} articles.")

    if idx == 1:
        filtered_news_train_df = filtered_df
    elif idx == 2:
        filtered_news_test_df = filtered_df

Processing ticker 1/516: A with 951 articles...
Completed processing ticker 1/516: A. Filtered articles: 924.
Processing ticker 2/516: AAL with 1 articles...
Completed processing ticker 2/516: AAL. Filtered articles: 1.
Processing ticker 3/516: AAPL with 1557 articles...
Completed processing ticker 3/516: AAPL. Filtered articles: 1339.
Processing ticker 4/516: ABBV with 1522 articles...
Completed processing ticker 4/516: ABBV. Filtered articles: 1438.
Processing ticker 5/516: ABI with 1 articles...
Completed processing ticker 5/516: ABI. Filtered articles: 1.
Processing ticker 6/516: ABNB with 314 articles...
Completed processing ticker 6/516: ABNB. Filtered articles: 292.
Processing ticker 7/516: ABT with 876 articles...
Completed processing ticker 7/516: ABT. Filtered articles: 840.
Processing ticker 8/516: ACGL with 459 articles...
Completed processing ticker 8/516: ACGL. Filtered articles: 423.
Processing ticker 9/516: ACN with 1913 articles...
Completed processing ticker 9/516: ACN. Filtered articles: 1863.
Processing ticker 10/516: ADBE with 814 articles...
Completed processing ticker 10/516: ADBE. Filtered articles: 792.
Processing ticker 11/516: ADI with 787 articles...
Completed processing ticker 11/516: ADI. Filtered articles: 754.
Processing ticker 12/516: ADM with 668 articles...
Completed processing ticker 12/516: ADM. Filtered articles: 646.
Processing ticker 13/516: ADP with 667 articles...
Completed processing ticker 13/516: ADP. Filtered articles: 616.
Processing ticker 14/516: ADSK with 610 articles...
Completed processing ticker 14/516: ADSK. Filtered articles: 588.
Processing ticker 15/516: AEE with 434 articles...
Completed processing ticker 15/516: AEE. Filtered articles: 422.
Processing ticker 16/516: AEP with 567 articles...
Completed processing ticker 16/516: AEP. Filtered articles: 524.
Processing ticker 17/516: AES with 610 articles...
Completed processing ticker 17/516: AES. Filtered articles: 575.
Processing ticker 18/516: AFL with 602 articles...
Completed processing ticker 18/516: AFL. Filtered articles: 548.
Processing ticker 19/516: AIG with 922 articles...
Completed processing ticker 19/516: AIG. Filtered articles: 861.
Processing ticker 20/516: AIZ with 528 articles...
Completed processing ticker 20/516: AIZ. Filtered articles: 491.
Processing ticker 21/516: AJG with 871 articles...
Completed processing ticker 21/516: AJG. Filtered articles: 830.
Processing ticker 22/516: AKAM with 802 articles...
Completed processing ticker 22/516: AKAM. Filtered articles: 778.
Processing ticker 23/516: ALB with 599 articles...
Completed processing ticker 23/516: ALB. Filtered articles: 557.
Processing ticker 24/516: ALGN with 520 articles...
Completed processing ticker 24/516: ALGN. Filtered articles: 487.
Processing ticker 25/516: ALL with 640 articles...
Completed processing ticker 25/516: ALL. Filtered articles: 610.
Processing ticker 26/516: ALLE with 496 articles...
Completed processing ticker 26/516: ALLE. Filtered articles: 478.
Processing ticker 27/516: AMAT with 610 articles...
Completed processing ticker 27/516: AMAT. Filtered articles: 569.
Processing ticker 28/516: AMCR with 419 articles...
Completed processing ticker 28/516: AMCR. Filtered articles: 383.
Processing ticker 29/516: AMD with 906 articles...
Completed processing ticker 29/516: AMD. Filtered articles: 841.
Processing ticker 30/516: AME with 489 articles...
Completed processing ticker 30/516: AME. Filtered articles: 476.
Processing ticker 31/516: AMGN with 1534 articles...
Completed processing ticker 31/516: AMGN. Filtered articles: 1384.
Processing ticker 32/516: AMP with 463 articles...
Completed processing ticker 32/516: AMP. Filtered articles: 435.
Processing ticker 33/516: AMT with 789 articles...
Completed processing ticker 33/516: AMT. Filtered articles: 697.
Processing ticker 34/516: AMTM with 81 articles...
Completed processing ticker 34/516: AMTM. Filtered articles: 67.
Processing ticker 35/516: AMZN with 1980 articles...
Completed processing ticker 35/516: AMZN. Filtered articles: 1775.
Processing ticker 36/516: ANET with 44 articles...
Completed processing ticker 36/516: ANET. Filtered articles: 39.
Processing ticker 37/516: ANSS with 655 articles...
Completed processing ticker 37/516: ANSS. Filtered articles: 640.
Processing ticker 38/516: AON with 673 articles...
Completed processing ticker 38/516: AON. Filtered articles: 647.
Processing ticker 39/516: AOS with 431 articles...
Completed processing ticker 39/516: AOS. Filtered articles: 410.
Processing ticker 40/516: APA with 612 articles...
Completed processing ticker 40/516: APA. Filtered articles: 570.
Processing ticker 41/516: APD with 886 articles...
Completed processing ticker 41/516: APD. Filtered articles: 820.
Processing ticker 42/516: APH with 487 articles...
Completed processing ticker 42/516: APH. Filtered articles: 477.
Processing ticker 43/516: APTV with 654 articles...
Completed processing ticker 43/516: APTV. Filtered articles: 615.
Processing ticker 44/516: ARE with 699 articles...
Completed processing ticker 44/516: ARE. Filtered articles: 601.
Processing ticker 45/516: ATO with 416 articles...
Completed processing ticker 45/516: ATO. Filtered articles: 375.
Processing ticker 46/516: AVA with 1 articles...
Completed processing ticker 46/516: AVA. Filtered articles: 1.
Processing ticker 47/516: AVB with 622 articles...
Completed processing ticker 47/516: AVB. Filtered articles: 556.
Processing ticker 48/516: AVGO with 805 articles...
Completed processing ticker 48/516: AVGO. Filtered articles: 699.
Processing ticker 49/516: AVY with 511 articles...
Completed processing ticker 49/516: AVY. Filtered articles: 489.
Processing ticker 50/516: AWK with 538 articles...
Completed processing ticker 50/516: AWK. Filtered articles: 517.
Processing ticker 51/516: AXON with 610 articles...
Completed processing ticker 51/516: AXON. Filtered articles: 578.
Processing ticker 52/516: AXP with 901 articles...
Completed processing ticker 52/516: AXP. Filtered articles: 847.
Processing ticker 53/516: AZO with 399 articles...
Completed processing ticker 53/516: AZO. Filtered articles: 377.
Processing ticker 54/516: BA with 2003 articles...
Completed processing ticker 54/516: BA. Filtered articles: 1858.
Processing ticker 55/516: BAC with 3752 articles...
Completed processing ticker 55/516: BAC. Filtered articles: 2087.
Processing ticker 56/516: BALL with 570 articles...
Completed processing ticker 56/516: BALL. Filtered articles: 543.
Processing ticker 57/516: BAX with 803 articles...
Completed processing ticker 57/516: BAX. Filtered articles: 753.
Processing ticker 58/516: BBU with 1 articles...
Completed processing ticker 58/516: BBU. Filtered articles: 1.
Processing ticker 59/516: BBY with 489 articles...
Completed processing ticker 59/516: BBY. Filtered articles: 467.
Processing ticker 60/516: BDX with 935 articles...
Completed processing ticker 60/516: BDX. Filtered articles: 861.
Processing ticker 61/516: BEN with 657 articles...
Completed processing ticker 61/516: BEN. Filtered articles: 619.
Processing ticker 62/516: BG with 512 articles...
Completed processing ticker 62/516: BG. Filtered articles: 489.
Processing ticker 63/516: BIIB with 1005 articles...
Completed processing ticker 63/516: BIIB. Filtered articles: 967.
Processing ticker 64/516: BK with 1163 articles...
Completed processing ticker 64/516: BK. Filtered articles: 983.
Processing ticker 65/516: BKNG with 431 articles...
Completed processing ticker 65/516: BKNG. Filtered articles: 383.
Processing ticker 66/516: BKR with 557 articles...
Completed processing ticker 66/516: BKR. Filtered articles: 539.
Processing ticker 67/516: BLDR with 435 articles...
Completed processing ticker 67/516: BLDR. Filtered articles: 391.
Processing ticker 68/516: BLK with 1557 articles...
Completed processing ticker 68/516: BLK. Filtered articles: 1524.
Processing ticker 69/516: BMY with 1899 articles...
Completed processing ticker 69/516: BMY. Filtered articles: 1758.
Processing ticker 70/516: BR with 725 articles...
Completed processing ticker 70/516: BR. Filtered articles: 703.
Processing ticker 71/516: BRO with 483 articles...
Completed processing ticker 71/516: BRO. Filtered articles: 460.
Processing ticker 72/516: BSX with 874 articles...
Completed processing ticker 72/516: BSX. Filtered articles: 796.
Processing ticker 73/516: BWA with 838 articles...
Completed processing ticker 73/516: BWA. Filtered articles: 814.
Processing ticker 74/516: BX with 1952 articles...
Completed processing ticker 74/516: BX. Filtered articles: 1911.
Processing ticker 75/516: BXP with 491 articles...
Completed processing ticker 75/516: BXP. Filtered articles: 472.
Processing ticker 76/516: C with 5283 articles...
Completed processing ticker 76/516: C. Filtered articles: 2948.
Processing ticker 77/516: CAG with 602 articles...
Completed processing ticker 77/516: CAG. Filtered articles: 569.
Processing ticker 78/516: CAH with 699 articles...
Completed processing ticker 78/516: CAH. Filtered articles: 650.
Processing ticker 79/516: CARR with 350 articles...
Completed processing ticker 79/516: CARR. Filtered articles: 301.
Processing ticker 80/516: CAT with 792 articles...
Completed processing ticker 80/516: CAT. Filtered articles: 759.
Processing ticker 81/516: CB with 939 articles...
Completed processing ticker 81/516: CB. Filtered articles: 894.
Processing ticker 82/516: CBOE with 605 articles...
Completed processing ticker 82/516: CBOE. Filtered articles: 576.
Processing ticker 83/516: CBRE with 735 articles...
Completed processing ticker 83/516: CBRE. Filtered articles: 704.
Processing ticker 84/516: CCI with 842 articles...
Completed processing ticker 84/516: CCI. Filtered articles: 581.
Processing ticker 85/516: CCL with 684 articles...
Completed processing ticker 85/516: CCL. Filtered articles: 630.
Processing ticker 86/516: CDNS with 1016 articles...
Completed processing ticker 86/516: CDNS. Filtered articles: 963.
Processing ticker 87/516: CDW with 486 articles...
Completed processing ticker 87/516: CDW. Filtered articles: 461.
Processing ticker 88/516: CE with 611 articles...
Completed processing ticker 88/516: CE. Filtered articles: 572.
Processing ticker 89/516: CEG with 179 articles...
Completed processing ticker 89/516: CEG. Filtered articles: 164.
Processing ticker 90/516: CF with 470 articles...
Completed processing ticker 90/516: CF. Filtered articles: 438.
Processing ticker 91/516: CFG with 631 articles...
Completed processing ticker 91/516: CFG. Filtered articles: 596.
Processing ticker 92/516: CHD with 493 articles...
Completed processing ticker 92/516: CHD. Filtered articles: 434.
Processing ticker 93/516: CHRW with 438 articles...
Completed processing ticker 93/516: CHRW. Filtered articles: 429.
Processing ticker 94/516: CHTR with 599 articles...
Completed processing ticker 94/516: CHTR. Filtered articles: 540.
Processing ticker 95/516: CI with 801 articles...
Completed processing ticker 95/516: CI. Filtered articles: 720.
Processing ticker 96/516: CINF with 345 articles...
Completed processing ticker 96/516: CINF. Filtered articles: 332.
Processing ticker 97/516: CL with 544 articles...
Completed processing ticker 97/516: CL. Filtered articles: 521.
Processing ticker 98/516: CLX with 483 articles...
Completed processing ticker 98/516: CLX. Filtered articles: 460.
Processing ticker 99/516: CMCSA with 1256 articles...
Completed processing ticker 99/516: CMCSA. Filtered articles: 1151.
Processing ticker 100/516: CME with 698 articles...
Completed processing ticker 100/516: CME. Filtered articles: 689.
Processing ticker 101/516: CMG with 589 articles...
Completed processing ticker 101/516: CMG. Filtered articles: 532.
Processing ticker 102/516: CMI with 740 articles...
Completed processing ticker 102/516: CMI. Filtered articles: 690.
Processing ticker 103/516: CMS with 463 articles...
Completed processing ticker 103/516: CMS. Filtered articles: 423.
Processing ticker 104/516: CNC with 709 articles...
Completed processing ticker 104/516: CNC. Filtered articles: 683.
Processing ticker 105/516: CNP with 461 articles...
Completed processing ticker 105/516: CNP. Filtered articles: 403.
Processing ticker 106/516: COF with 814 articles...
Completed processing ticker 106/516: COF. Filtered articles: 761.
Processing ticker 107/516: COO with 385 articles...
Completed processing ticker 107/516: COO. Filtered articles: 365.
Processing ticker 108/516: COP with 725 articles...
Completed processing ticker 108/516: COP. Filtered articles: 690.
Processing ticker 109/516: COR with 638 articles...
Completed processing ticker 109/516: COR. Filtered articles: 590.
Processing ticker 110/516: COST with 741 articles...
Completed processing ticker 110/516: COST. Filtered articles: 706.
Processing ticker 111/516: CPAY with 461 articles...
Completed processing ticker 111/516: CPAY. Filtered articles: 432.
Processing ticker 112/516: CPB with 644 articles...
Completed processing ticker 112/516: CPB. Filtered articles: 587.
Processing ticker 113/516: CPRT with 340 articles...
Completed processing ticker 113/516: CPRT. Filtered articles: 331.
Processing ticker 114/516: CPT with 472 articles...
Completed processing ticker 114/516: CPT. Filtered articles: 441.
Processing ticker 115/516: CRL with 601 articles...
Completed processing ticker 115/516: CRL. Filtered articles: 538.
Processing ticker 116/516: CRM with 1574 articles...
Completed processing ticker 116/516: CRM. Filtered articles: 1412.
Processing ticker 117/516: CRWD with 396 articles...
Completed processing ticker 117/516: CRWD. Filtered articles: 333.
Processing ticker 118/516: CSCO with 2054 articles...
Completed processing ticker 118/516: CSCO. Filtered articles: 1878.
Processing ticker 119/516: CSGP with 424 articles...
Completed processing ticker 119/516: CSGP. Filtered articles: 391.
Processing ticker 120/516: CSX with 603 articles...
Completed processing ticker 120/516: CSX. Filtered articles: 564.
Processing ticker 121/516: CTAS with 424 articles...
Completed processing ticker 121/516: CTAS. Filtered articles: 384.
Processing ticker 122/516: CTLT with 483 articles...
Completed processing ticker 122/516: CTLT. Filtered articles: 442.
Processing ticker 123/516: CTRA with 446 articles...
Completed processing ticker 123/516: CTRA. Filtered articles: 408.
Processing ticker 124/516: CTSH with 791 articles...
Completed processing ticker 124/516: CTSH. Filtered articles: 772.
Processing ticker 125/516: CTVA with 285 articles...
Completed processing ticker 125/516: CTVA. Filtered articles: 271.
Processing ticker 126/516: CVS with 947 articles...
Completed processing ticker 126/516: CVS. Filtered articles: 845.
Processing ticker 127/516: CVX with 877 articles...
Completed processing ticker 127/516: CVX. Filtered articles: 800.
Processing ticker 128/516: CZR with 502 articles...
Completed processing ticker 128/516: CZR. Filtered articles: 448.
Processing ticker 129/516: D with 753 articles...
Completed processing ticker 129/516: D. Filtered articles: 711.
Processing ticker 130/516: DAL with 939 articles...
Completed processing ticker 130/516: DAL. Filtered articles: 881.
Processing ticker 131/516: DAY with 323 articles...
Completed processing ticker 131/516: DAY. Filtered articles: 284.
Processing ticker 132/516: DD with 932 articles...
Completed processing ticker 132/516: DD. Filtered articles: 870.
Processing ticker 133/516: DE with 585 articles...
Completed processing ticker 133/516: DE. Filtered articles: 565.
Processing ticker 134/516: DECK with 367 articles...
Completed processing ticker 134/516: DECK. Filtered articles: 326.
Processing ticker 135/516: DELL with 873 articles...
Completed processing ticker 135/516: DELL. Filtered articles: 772.
Processing ticker 136/516: DFS with 766 articles...
Completed processing ticker 136/516: DFS. Filtered articles: 610.
Processing ticker 137/516: DG with 528 articles...
Completed processing ticker 137/516: DG. Filtered articles: 496.
Processing ticker 138/516: DGX with 663 articles...
Completed processing ticker 138/516: DGX. Filtered articles: 643.
Processing ticker 139/516: DHI with 483 articles...
Completed processing ticker 139/516: DHI. Filtered articles: 456.
Processing ticker 140/516: DHR with 622 articles...
Completed processing ticker 140/516: DHR. Filtered articles: 549.
Processing ticker 141/516: DIS with 896 articles...
Completed processing ticker 141/516: DIS. Filtered articles: 700.
Processing ticker 142/516: DLR with 798 articles...
Completed processing ticker 142/516: DLR. Filtered articles: 753.
Processing ticker 143/516: DLTR with 376 articles...
Completed processing ticker 143/516: DLTR. Filtered articles: 336.
Processing ticker 144/516: DOC with 587 articles...
Completed processing ticker 144/516: DOC. Filtered articles: 547.
Processing ticker 145/516: DOV with 554 articles...
Completed processing ticker 145/516: DOV. Filtered articles: 531.
Processing ticker 146/516: DOW with 313 articles...
Completed processing ticker 146/516: DOW. Filtered articles: 297.
Processing ticker 147/516: DPZ with 528 articles...
Completed processing ticker 147/516: DPZ. Filtered articles: 501.
Processing ticker 148/516: DRI with 593 articles...
Completed processing ticker 148/516: DRI. Filtered articles: 527.
Processing ticker 149/516: DTE with 606 articles...
Completed processing ticker 149/516: DTE. Filtered articles: 573.
Processing ticker 150/516: DUK with 867 articles...
Completed processing ticker 150/516: DUK. Filtered articles: 782.
Processing ticker 151/516: DVA with 471 articles...
Completed processing ticker 151/516: DVA. Filtered articles: 442.
Processing ticker 152/516: DVN with 589 articles...
Completed processing ticker 152/516: DVN. Filtered articles: 547.
Processing ticker 153/516: DXCM with 499 articles...
Completed processing ticker 153/516: DXCM. Filtered articles: 484.
Processing ticker 154/516: EA with 644 articles...
Completed processing ticker 154/516: EA. Filtered articles: 596.
Processing ticker 155/516: EBAY with 876 articles...
Completed processing ticker 155/516: EBAY. Filtered articles: 793.
Processing ticker 156/516: ECL with 734 articles...
Completed processing ticker 156/516: ECL. Filtered articles: 696.
Processing ticker 157/516: ED with 376 articles...
Completed processing ticker 157/516: ED. Filtered articles: 359.
Processing ticker 158/516: EFX with 947 articles...
Completed processing ticker 158/516: EFX. Filtered articles: 833.
Processing ticker 159/516: EG with 429 articles...
Completed processing ticker 159/516: EG. Filtered articles: 402.
Processing ticker 160/516: EIX with 406 articles...
Completed processing ticker 160/516: EIX. Filtered articles: 395.
Processing ticker 161/516: EL with 558 articles...
Completed processing ticker 161/516: EL. Filtered articles: 503.
Processing ticker 162/516: ELV with 694 articles...
Completed processing ticker 162/516: ELV. Filtered articles: 645.
Processing ticker 163/516: EMN with 588 articles...
Completed processing ticker 163/516: EMN. Filtered articles: 567.
Processing ticker 164/516: EMR with 732 articles...
Completed processing ticker 164/516: EMR. Filtered articles: 684.
Processing ticker 165/516: ENPH with 635 articles...
Completed processing ticker 165/516: ENPH. Filtered articles: 582.
Processing ticker 166/516: EOG with 495 articles...
Completed processing ticker 166/516: EOG. Filtered articles: 451.
Processing ticker 167/516: EPAM with 345 articles...
Completed processing ticker 167/516: EPAM. Filtered articles: 336.
Processing ticker 168/516: EQIX with 1037 articles...
Completed processing ticker 168/516: EQIX. Filtered articles: 877.
Processing ticker 169/516: EQR with 504 articles...
Completed processing ticker 169/516: EQR. Filtered articles: 494.
Processing ticker 170/516: EQT with 708 articles...
Completed processing ticker 170/516: EQT. Filtered articles: 599.
Processing ticker 171/516: ERIE with 372 articles...

In [29]:
filtered_news_train_df

,date,title,source,ticker
0,2014-01-06,Agilent Technologies Introduces New Version of...,Business Wire,A
1,2014-01-06,Agilent Technologies Introduces ICP-MS and MP-...,Business Wire,A
2,2014-01-08,Agilent Technologies Inc. Introduces New Exter...,Business Wire,A
3,2014-01-09,AT4 Wireless Selects Agilent Technologies Test...,Business Wire,A
4,2014-01-09,Agilent Technologies Introduces First USB 3.0 ...,Other,A
...,...,...,...,...
332971,2023-11-02,"Zoetis Inc., Q3 2023 Earnings Call, Nov 02, 2023",Business Wire,ZTS
332972,2023-11-02,Zoetis Inc. Provides Earnings Guidance for the...,Business Wire,ZTS
332973,2023-11-02,Zoetis Inc. Reports Earnings Results for the T...,S&P Capital IQ Financials Database,ZTS
332974,2023-11-28,Zoetis Inc. Presents at Piper Sandler 35th Ann...,PR Newswire; Business Wire; Other; GlobeNewswi...,ZTS
332975,2023-12-07,Zoetis Inc. Declares Dividend for the First Qu...,Business Wire,ZTS

In [30]:
filtered_news_test_df

,date,title,source,ticker
0,2024-01-08,"Agilent Technologies, Inc. Presents at BIO Par...",Business Wire; GlobeNewswire; Company Website,A
1,2024-01-09,"Agilent Technologies, Inc. Presents at J.P. Mo...",PR Newswire; Business Wire; Other; GlobeNewswi...,A
2,2024-01-16,"Agilent Technologies, Inc. Announces New Prote...",Business Wire,A
3,2024-01-16,"Agilent Technologies, Inc. Presents at 23rd An...",Company Website,A
4,2024-01-17,"Agilent Technologies, Inc. - Special Call",Company Website,A
...,...,...,...,...
29276,2024-11-04,Zoetis Inc. Raises Revenue Guidance for the Fu...,Business Wire,ZTS
29277,2024-11-11,Zoetis Inc. Presents at Fortune Global Forum 2...,PR Newswire,ZTS
29278,2024-11-11,Zoetis Inc. Announces Executive Changes,Business Wire,ZTS
29279,2024-11-20,Zoetis Inc. Presents at Jefferies London Healt...,PR Newswire; Business Wire; Other; GlobeNewswi...,ZTS
29280,2024-12-03,Zoetis Inc. Presents at Piper Sandler 36th Ann...,PR Newswire; Business Wire; GlobeNewswire; Com...,ZTS

In [31]:
filtered_news_train_df.to_csv("Data Updated/filtered_news_train_df.csv")
filtered_news_test_df.to_csv("Data Updated/filtered_news_test_df.csv")

# Stocks Data Download
- Note that this is not the returns of the stocks data
- Let's focus on periods 2023-01-01 to 2024-12-01 for this project

In [99]:
stocks = yf.download(tickers, threads=True, group_by='ticker', start='2014-01-01', end='2024-12-01', multi_level_index=False)

[*********************100%***********************]  503 of 503 completed

2 Failed downloads:
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2014-01-01 -> 2024-12-01)')

In [100]:
stocks

Ticker             JNJ                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2014-01-02   91.139999   91.730003   91.010002   91.029999   67.211365
2014-01-03   91.290001   92.220001   91.260002   91.849998   67.816818
2014-01-06   91.930000   92.750000   91.870003   92.330002   68.171196
2014-01-07   93.040001   94.620003   92.989998   94.290001   69.618393
2014-01-08   94.169998   94.599998   93.879997   94.160004   69.522385
...                ...         ...         ...         ...         ...
2024-11-22  155.899994  157.119995  154.110001  155.169998  153.934845
2024-11-25  155.169998  157.039993  155.139999  155.779999  154.539993
2024-11-26  155.160004  155.250000  153.160004  154.520004  154.520004
2024-11-27  154.630005  156.630005  154.600006  155.399994  155.399994
2024-11-29  154.889999  155.669998  154.169998  155.009995  155.009995

Ticker                       FRT                                      ...  \
Price         Volume        Open        High         Low       Close  ...
Date                                                                  ...
2014-01-02   5919600  101.379997  101.839996  100.370003  100.900002  ...
2014-01-03   5637600  101.129997  102.279999  100.970001  101.930000  ...
2014-01-06   7443500  103.050003  103.580002  102.269997  103.260002  ...
2014-01-07  11063300  103.339996  104.360001  101.800003  103.970001  ...
2014-01-08   9096700  103.709999  103.919998  102.070000  103.470001  ...
...              ...         ...         ...         ...         ...  ...
2024-11-22   8266000  114.970001  115.199997  114.430000  114.860001  ...
2024-11-25  12256200  115.669998  116.580002  115.330002  115.980003  ...
2024-11-26   5683500  116.070000  116.209999  115.150002  115.900002  ...
2024-11-27   4140400  116.629997  118.000000  116.419998  117.529999  ...
2024-11-29   5687800  117.599998  118.089996  116.610001  116.650002  ...

Ticker             EFX                                          HUM  \
Price              Low       Close   Adj Close   Volume        Open
Date
2014-01-02   68.199997   68.449997   61.218979   336300  102.760002
2014-01-03   68.550003   68.900002   61.621445   314800  102.860001
2014-01-06   68.190002   68.260002   61.049038   284800  102.300003
2014-01-07   68.320000   68.730003   61.469414   320900   98.720001
2014-01-08   67.910004   68.739998   61.478336   445800  100.660004
...                ...         ...         ...      ...         ...
2024-11-22  252.660004  253.580002  253.580002   773100  296.000000
2024-11-25  256.170013  263.890015  263.890015  1732000  312.000000
2024-11-26  256.829987  258.940002  258.940002  1113900  304.000000
2024-11-27  260.529999  261.190002  261.190002   559900  296.670013
2024-11-29  261.390015  261.559998  261.559998   734600  294.920013

Ticker
Price             High         Low       Close   Adj Close   Volume
Date
2014-01-02  103.879997  102.300003  102.839996   95.121132  1393500
2014-01-03  103.040001  101.580002  101.760002   94.122238  1234400
2014-01-06  102.379997   99.959999  100.760002   93.197266  1850200
2014-01-07  101.349998   98.500000  100.550003   93.003052  2561700
2014-01-08  100.660004   98.949997   99.400002   91.939339  2332700
...                ...         ...         ...         ...      ...
2024-11-22  303.029999  295.410004  298.109985  298.109985  1450600
2024-11-25  313.000000  303.630005  304.179993  304.179993  2656600
2024-11-26  304.000000  294.470001  295.589996  295.589996  1556000
2024-11-27  299.190002  294.959991  296.679993  296.679993   995700
2024-11-29  298.920013  294.850006  296.380005  296.380005   533900

[2747 rows x 3018 columns]

In [ ]:
# ticker_tz_df = pd.DataFrame()
# for t in tickers:
#     try:
#         ticker_info = yf.Ticker(t)
#         ticker_tz = ticker_info.info['timeZoneShortName']
#         ticker_tz_temp_df = pd.DataFrame({'Ticker':[t], 'tz':[ticker_tz]})
#         ticker_tz_df = pd.concat([ticker_tz_df, ticker_tz_temp_df])
#     except:
#         print(f'No timezone info for {t}')

No timezone info for BRK.B

In [ ]:
# print(f'Timezones of SPY stocks include: {ticker_tz_df.tz.unique()}')

Timezones of SPY stocks include: ['EST']

In [101]:
# Convert Stocks timezone to UTC 0
stocks.index = (
    stocks.index
    .tz_localize("EST")
    .tz_convert("UTC")
    .tz_localize(None)
    .normalize()
)

In [102]:
market = yf.download(["SPY"], threads=True, group_by='ticker', start='2014-01-01', end='2024-12-01', multi_level_index=False)

[*********************100%***********************]  1 of 1 completed

In [103]:
market

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-01-02,183.979996,184.070007,182.479996,182.919998,151.242920,119636900
2014-01-03,183.229996,183.600006,182.630005,182.889999,151.218094,81390600
2014-01-06,183.490005,183.559998,182.080002,182.360001,150.779907,108028200
2014-01-07,183.089996,183.789993,182.949997,183.479996,151.705978,86144200
2014-01-08,183.449997,183.830002,182.889999,183.520004,151.739014,96582300
...,...,...,...,...,...,...
2024-11-22,593.659973,596.150024,593.150024,595.510010,595.510010,38226400
2024-11-25,599.520020,600.859985,595.200012,597.530029,597.530029,42441400
2024-11-26,598.799988,601.330017,598.070007,600.650024,600.650024,45621300
2024-11-27,600.460022,600.849976,597.280029,598.830017,598.830017,34000200
2024-11-29,599.659973,603.349976,599.380005,602.549988,602.549988,30177400

In [104]:
market.index = (
    market.index
    .tz_localize("EST")
    .tz_convert("UTC")
    .tz_localize(None)
    .normalize()
)

In [105]:
stocks

Ticker             JNJ                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2014-01-02   91.139999   91.730003   91.010002   91.029999   67.211365
2014-01-03   91.290001   92.220001   91.260002   91.849998   67.816818
2014-01-06   91.930000   92.750000   91.870003   92.330002   68.171196
2014-01-07   93.040001   94.620003   92.989998   94.290001   69.618393
2014-01-08   94.169998   94.599998   93.879997   94.160004   69.522385
...                ...         ...         ...         ...         ...
2024-11-22  155.899994  157.119995  154.110001  155.169998  153.934845
2024-11-25  155.169998  157.039993  155.139999  155.779999  154.539993
2024-11-26  155.160004  155.250000  153.160004  154.520004  154.520004
2024-11-27  154.630005  156.630005  154.600006  155.399994  155.399994
2024-11-29  154.889999  155.669998  154.169998  155.009995  155.009995

Ticker                       FRT                                      ...  \
Price         Volume        Open        High         Low       Close  ...
Date                                                                  ...
2014-01-02   5919600  101.379997  101.839996  100.370003  100.900002  ...
2014-01-03   5637600  101.129997  102.279999  100.970001  101.930000  ...
2014-01-06   7443500  103.050003  103.580002  102.269997  103.260002  ...
2014-01-07  11063300  103.339996  104.360001  101.800003  103.970001  ...
2014-01-08   9096700  103.709999  103.919998  102.070000  103.470001  ...
...              ...         ...         ...         ...         ...  ...
2024-11-22   8266000  114.970001  115.199997  114.430000  114.860001  ...
2024-11-25  12256200  115.669998  116.580002  115.330002  115.980003  ...
2024-11-26   5683500  116.070000  116.209999  115.150002  115.900002  ...
2024-11-27   4140400  116.629997  118.000000  116.419998  117.529999  ...
2024-11-29   5687800  117.599998  118.089996  116.610001  116.650002  ...

Ticker             EFX                                          HUM  \
Price              Low       Close   Adj Close   Volume        Open
Date
2014-01-02   68.199997   68.449997   61.218979   336300  102.760002
2014-01-03   68.550003   68.900002   61.621445   314800  102.860001
2014-01-06   68.190002   68.260002   61.049038   284800  102.300003
2014-01-07   68.320000   68.730003   61.469414   320900   98.720001
2014-01-08   67.910004   68.739998   61.478336   445800  100.660004
...                ...         ...         ...      ...         ...
2024-11-22  252.660004  253.580002  253.580002   773100  296.000000
2024-11-25  256.170013  263.890015  263.890015  1732000  312.000000
2024-11-26  256.829987  258.940002  258.940002  1113900  304.000000
2024-11-27  260.529999  261.190002  261.190002   559900  296.670013
2024-11-29  261.390015  261.559998  261.559998   734600  294.920013

Ticker
Price             High         Low       Close   Adj Close   Volume
Date
2014-01-02  103.879997  102.300003  102.839996   95.121132  1393500
2014-01-03  103.040001  101.580002  101.760002   94.122238  1234400
2014-01-06  102.379997   99.959999  100.760002   93.197266  1850200
2014-01-07  101.349998   98.500000  100.550003   93.003052  2561700
2014-01-08  100.660004   98.949997   99.400002   91.939339  2332700
...                ...         ...         ...         ...      ...
2024-11-22  303.029999  295.410004  298.109985  298.109985  1450600
2024-11-25  313.000000  303.630005  304.179993  304.179993  2656600
2024-11-26  304.000000  294.470001  295.589996  295.589996  1556000
2024-11-27  299.190002  294.959991  296.679993  296.679993   995700
2024-11-29  298.920013  294.850006  296.380005  296.380005   533900

[2747 rows x 3018 columns]

In [106]:
stocks.to_csv("Data Updated/stocks_data.csv")

In [107]:
market

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-01-02,183.979996,184.070007,182.479996,182.919998,151.242920,119636900
2014-01-03,183.229996,183.600006,182.630005,182.889999,151.218094,81390600
2014-01-06,183.490005,183.559998,182.080002,182.360001,150.779907,108028200
2014-01-07,183.089996,183.789993,182.949997,183.479996,151.705978,86144200
2014-01-08,183.449997,183.830002,182.889999,183.520004,151.739014,96582300
...,...,...,...,...,...,...
2024-11-22,593.659973,596.150024,593.150024,595.510010,595.510010,38226400
2024-11-25,599.520020,600.859985,595.200012,597.530029,597.530029,42441400
2024-11-26,598.799988,601.330017,598.070007,600.650024,600.650024,45621300
2024-11-27,600.460022,600.849976,597.280029,598.830017,598.830017,34000200
2024-11-29,599.659973,603.349976,599.380005,602.549988,602.549988,30177400

In [108]:
market.to_csv("Data Updated/market_data.csv")